image: nberlette/gitpod-enhanced:latest
tasks:
  - name: "Preview"
    before: pnpm install
    command: pnpm run dev
ports:
  - port: 3000
    onOpen: notify
  - port: 5000
    onOpen: notify
github:
  prebuilds:
    branches: true
    addLabel: true
    addBadge: true
vscode:
  extensions:
    - "svelte.svelte-vscode"
    - "esbenp.prettier-vscode"
    - "dbaeumer.vscode-eslint"
    - "voorjaar.windicss-intellisense"
    - "eamodio.gitlens"